name: 'Code Quality Validation'

on:
  push:
    branches:
      - 'feature/**'
      - 'refactor/**'

jobs:
  code_quality:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Get Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Get dependencies
        run: pnpm install

      - name: Run lint validations
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build application
        run: pnpm build
